export const enum IndicatorType {
  HEART_RATE_VARIABILITY = 'HEART_RATE_VARIABILITY',
  SYSTOLIC_BLOOD_PRESSURE = 'SYSTOLIC_BLOOD_PRESSURE',
  ASYSTOLIC_BLOOD_PRESSURE = 'ASYSTOLIC_BLOOD_PRESSURE',
  VISERAL_FAT = 'VISERAL_FAT'
}
