export const enum SourceType {
  HEART_RATE_MONITOR = 'HEART_RATE_MONITOR',
  SPORTS_WATCH = 'SPORTS_WATCH',
  BLOOD_PRESSURE_CUFF = 'BLOOD_PRESSURE_CUFF',
  FULL_BODY_IMAGING_DEVICE = 'FULL_BODY_IMAGING_DEVICE',
  TANITA_MACHINE = 'TANITA_MACHINE'
}
